// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmPIOp5LeD1V-bf4V4lyidoCqXr0Rfa-U',
    appId: '1:241824085064:android:ee402e138de53fdf43547d',
    messagingSenderId: '241824085064',
    projectId: 'mygamestrackerdb-d45ad',
    storageBucket: 'mygamestrackerdb-d45ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSsVhwoSZ-_b4pd0X1kvz1F91xA6X3UZs',
    appId: '1:241824085064:ios:3e493bdb28d917c643547d',
    messagingSenderId: '241824085064',
    projectId: 'mygamestrackerdb-d45ad',
    storageBucket: 'mygamestrackerdb-d45ad.appspot.com',
    iosClientId: '241824085064-ng4noveu57vfv7uq1pe2cb7trp0r0p46.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGamesTracker',
  );
}
